---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/news
  label: Posts
  create: documents
  match: "**/*"
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - page
- type: heading
  label: Tools
- type: document
  path: content/nav.json
  label: Menus
- type: document
  path: content/main.json
  label: Texts & Settings
upload_dir: public/static/uploads
public_path: "/static/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
